misitio/encuestas/urls.py
from django.urls import path
from . import views

app_name = 'encuestas'
urlpatterns = [
    # ej: /encuestas/
    path('', views.VistaIndice.as_view(), name='indice'),
    # ej: /encuestas/5/
    path('<int:pk>/', views.VistaDetalle.as_view(), name='detalle'),
    # ej: /encuestas/5/resultados/
    path('<int:pk>/resultados/', views.VistaResultados.as_view(), name='resultados'),
    # ej: /encuestas/5/voto/
    path('<int:id_pregunta>/voto/', views.voto, name='voto'),
]

misitio/misitio/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('encuestas/', include('encuestas.urls')),
]

misitio/encuestas/models.py
from django.db import models
from django.utils import timezone

import datetime


class Pregunta(models.Model):
    texto_pregunta = models.CharField(max_length=200)
    fecha_pub = models.DateField('Fecha de Publicación')

    def __str__(self):
        return self.texto_pregunta

    def fue_publicada_recien(self):
        ahora = timezone.now().date()
        return ahora - datetime.timedelta(days=1) <= self.fecha_pub <= ahora


class Eleccion(models.Model):
    pregunta = models.ForeignKey(Pregunta, on_delete=models.CASCADE)
    texto_eleccion = models.CharField(max_length=200)
    votos = models.IntegerField(default=0)

    def __str__(self):
        return self.texto_eleccion

misitio/encuestas/views.py
from .models import Eleccion, Pregunta

from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils import timezone
from django.views import generic


class VistaIndice(generic.ListView):
    context_object_name = 'lista_preguntas_recientes'
    template_name = 'encuestas/index.html'

    def get_queryset(self):
        """Devuelve las últimas cinco preguntas publicadas."""
        return Pregunta.objects.filter(
            fecha_pub__lte=timezone.now()
        ).order_by('-fecha_pub')[:5]


class VistaDetalle(generic.DetailView):
    model = Pregunta
    template_name = 'encuestas/detalle.html'

    def get_queryset(self):
        """Excluye cualquier pregunta que no se haya publicado todavía."""
        return Pregunta.objects.filter(fecha_pub__lte=timezone.now())


class VistaResultados(generic.DetailView):
    model = Pregunta
    template_name = 'encuestas/resultados.html'


def voto(peticion, id_pregunta):
    pregunta = get_object_or_404(Pregunta, pk=id_pregunta)
    try:
        eleccion_seleccionada = pregunta.eleccion_set.get(pk=peticion.POST['eleccion'])
    except(KeyError, Eleccion.DoesNotExist):
        return render(peticion, 'encuestas/detalle.html', {
            'pregunta': pregunta,
            'mensaje_error': "No seleccionaste una opción."
        })
    else:
        eleccion_seleccionada.votos += 1
        eleccion_seleccionada.save()
        # Siempre devolver una HttpResponseRedirect después de manipular exitosamente datos POST. Esto previene que los
        # datos sean publicados dos veces si un usuario da click en el botón Atrás.
        return HttpResponseRedirect(reverse('encuestas:resultados', args=(pregunta.id,)))

misitio/encuestas/templates/encuestas/detalle.html
<!DOCTYPE html>
<html lang="es-ec">

<head>
<meta charset="utf-8">
<title>Detalle</title>
</head>

<body>
<h1>{{ pregunta.texto_pregunta }}</h1>

{% if mensaje_error %}<p><strong>{{ mensaje_error }}</strong></p>{% endif %}

<form action="{% url 'encuestas:voto' pregunta.id %}" method="post">
    {% csrf_token %}
    {% for eleccion in pregunta.eleccion_set.all %}
        <input type="radio" name="eleccion" id="eleccion{{ forloop.counter }}" value="{{ eleccion.id }}">
        <label for="eleccion{{ forloop.counter }}">{{ eleccion.texto_eleccion }}</label><br>
    {% endfor %}
    <input type="submit" value="voto">
</form>
</body>

</html>

misitio/encuestas/templates/encuestas/index.html
<!DOCTYPE html>
<html lang="es-ec">

<head>
<meta charset="utf-8">
<title>Preguntas Recientes</title>
</head>

<body>
{%  if lista_preguntas_recientes %}
    <ul>
        {% for pregunta in lista_preguntas_recientes %}
            <li><a href="{% url 'encuestas:detalle' pregunta.id %}">{{ pregunta.texto_pregunta }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>No hay encuestas disponibles.</p>
{% endif %}
</body>

</html>

misitio/encuestas/templates/encuestas/resultados.html
<!DOCTYPE html>
<html lang="es-ec">

<head>
<meta charset="utf-8">
<title>Resultados</title>
</head>

<body>
<h1>{{ pregunta.texto_pregunta }}</h1>

<ul>
    {% for eleccion in pregunta.eleccion_set.all %}
        <li>{{ eleccion.texto_eleccion }} -- {{ eleccion.votos }} voto{{ eleccion.votos|pluralize }}</li>
    {% endfor %}
</ul>

<a href="{% url 'encuestas:detalle' pregunta.id %}">¿Votar otra vez?</a>
</body>

</html>